### PR TITLE
Update Sweep

### LINKED ISSUE #45: `sweep.py` should do everything through `tx`
With the merging of #42, we should sweep through error and FEC parameters directly through `tx`. This will actually make the script much simpler. It might still be a good idea to keep around the ability to use `encode` and `decode`? On the other hand, we might want to retire those completely -- something to discuss and decide.

### PR DESCRIPTION
**Pull request by Cam57**
Updated the sweep.py script to only use TX. Apologies for the delay.

### CODE REVIEW

**Review by digital-nomad8620 — CHANGES_REQUESTED** [review]
Can we just remove the commented blocks of code? I don't think they're necessary anymore. Other than that it looks good! I tried running it and it looks like rx is failing to map the temporary file to memory? I'm not sure why that's happening but I don't think it's related to your PR at all.

**Comment by Cam57** [comment]
I think I found another minor issue with the script that occurs prior to the update. It looks like the script can't find some of the directories and is fail to map to memory.

To Reproduce:

Here is the command I used:  python3  test/sweep.py -c 0.5 0.8 0.1 -e 0.001 0.01 0.001 -p 0.01 0.1 0.01 -o sweeps -s test.raw   
Test Data: daisy.bmp (found in test/data)

Results:
[ INFO ][ transmitter ] : DxWifi Transmitter Settings
	Device:              mon0
	PA Enabled:          0
	Transmit Timeout:    -1
	Redundant Ctrl:      0
	Data Rate:           1Mbps
	RTAP flags:          0x10
	RTAP Tx flags:       0x8
[ ERROR ][ tx ] : Failed to open file: sweeps/CodeRate0.5/file.encoded - No such file or directory[ INFO ][ transmitter ] : DxWifi transmitter closed

[ INFO ][ receiver ] : DxWifi Receiver Settings
	Device:                   mon0
	Capture Timeout:          -1s
	Packet Buffer Size:       5242880
	Max Hamming Distance:     20
	Ordered:                  0
	Add-noise:                0
	Filter:                   (null)
	Optimize:                 1
	Snapshot Length:          65535
	PCAP Buffer Timeout:      20ms
	Dispatch Count:           1
	Datalink Type:            802.11 plus radiotap header
[ INFO ][ receiver ] : Starting packet capture...[ INFO ][ receiver ] : DxWiFi Reciever capture ended[ WARN ][ receiver ] : Failed to gather capture stats from PCAP[ FATAL ][ rx ] : rx.c:174 Assertion `encoded_data != MAP_FAILED` failed : Failed to map file to memory - Invalid argument

**Comment by khanu263** [comment]
It looks like this branch doesn't include the bugfixes that were merged in this week. Might be good to rebase on `master`. Also, @AlexanderJDupree, is code rate fixed now in `tx` or is that still a sweep-able parameter?

**Comment by digital-nomad8620** [comment]
@khanu263 ahhh yes, lots of changes were made in #48. We should rebase and verify that the problem still exists.

**Review by digital-nomad8620 — APPROVED** [review]

**Review by khanu263 — APPROVED** [review]
I fixed the code rate sweep and cleaned up some extra comments. I also tried to figure out the interleaving of `stdout` and `stderr` in `subprocess` so the output logs would look nicer, but it ended being more complicated than it's worth, so I just left a standing `TODO` at the top.

I think this is ready to merge now.

**Review by ghost — APPROVED** [review]
Looks good!

**Comment by digital-nomad8620** [comment]
> I fixed the code rate sweep and cleaned up some extra comments. I also tried to figure out the interleaving of `stdout` and `stderr` in `subprocess` so the output logs would look nicer, but it ended being more complicated than it's worth, so I just left a standing `TODO` at the top.
> 
> I think this is ready to merge now.

@khanu263 do you think it would be easier for subprocess it all the logs went to stdout? I can add that in very easily.

**Comment by khanu263** [comment]
@AlexanderJDupree it would definitely be easier -- not only for this script but whatever other coordinating scripts in the future use output from `tx` and `rx`. Not at all critical but absolutely would be nice to have.

**Pull request merged**
